import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '../register/globals.css'
import '../styles/wish.css'
import '../styles/account.css'
import '../styles/form.css'
import '../styles/bg.css'
import '../styles/reset.css'
import '../styles/general.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
